apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- producer.yaml

images:
- name: opensky-producer 
  newName: ghcr.io/kademeray/data-engineer-end-to-end-project/opensky-producer
  newTag: latest