apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensky-producer
  namespace: kafka   # Wir lassen ihn im kafka Namespace, das ist okay
  labels:
    app: opensky-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensky-producer
  template:
    metadata:
      labels:
        app: opensky-producer
    spec:
      containers:
      - name: producer
        # Wir nutzen dein Image von GitHub
        image: ghcr.io/kademeray/data-engineer-end-to-end-project/opensky-producer:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        # ðŸ‘‡ DAS HAT GEFEHLT: Wo ist Kafka?
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        - name: KAFKA_TOPIC
          value: "flight_raw_data"