apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensky-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensky-producer
  template:
    metadata:
      labels:
        app: opensky-producer
    spec:
      containers:
      - name: producer
        # ðŸ‘‡ KORREKTUR: Der lange Pfad mit Repo-Namen
        image: ghcr.io/kademeray/data-engineer-end-to-end-project/opensky-producer:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"