apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- processor.yaml

images:
- name: opensky-spark-processor
  newName: ghcr.io/kademeray/data-engineer-end-to-end-project/opensky-spark-processor
  newTag: 4ea5b41
