apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensky-producer
  namespace: argocd
  annotations:
    # ðŸ‘‡ WICHTIG: Hier steht jetzt der korrekte, lange Name (alles klein)!
    argocd-image-updater.argoproj.io/image-list: myproducer=ghcr.io/kademeray/data-engineer-end-to-end-project/opensky-producer
    argocd-image-updater.argoproj.io/myproducer.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KademEray/Data-Engineer-End-to-End-Project.git
    targetRevision: main
    path: infrastructure/k8s/producer-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true