apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensky-producer
  namespace: argocd
  # ðŸ‘‡ NEU: Diese Annotations steuern das Update
  annotations:
    # 1. Image Alias definieren (DEIN_USER anpassen!)
    argocd-image-updater.argoproj.io/image-list: myproducer=ghcr.io/KademEray/opensky-producer
    # 2. Strategie: PrÃ¼fe auf neuen Digest (Hash), da Tag immer 'latest' ist
    argocd-image-updater.argoproj.io/myproducer.update-strategy: digest
    # 3. Methode: Schreibe Ã„nderung zurÃ¼ck ins Git
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # ðŸ‘‡ HIER DEINEN NAMEN EINTRAGEN
    repoURL: https://github.com/KademEray/Data-Engineer-End-to-End-Project.git
    targetRevision: main
    path: infrastructure/k8s/producer-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true